import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";

const prompt = Prompt({
  subsets: ["latin", "thai"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Food Tracker App",
  description: "Generated by DTI TEWAN SAU",
  keywords: ["Food", "Tracker", "อาหาร", "สุขภาพ", "Health"],
  icons: {
    icon: "/vercel.svg",
  },
  authors: [{ name: "DTI TEWAN SAU", 
    url: "https://tewansau.com",
  }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={prompt.className}>{children}</body>
    </html>
  );
}
